server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/java9-grup2/HRMS-GIT-CONFIG-REPO.git"
          default-label: main
          skip-ssl-validation: true
          username: ${java9gitconfigusername}
          password: ${java9gitconfigpassword}
