server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: auth-service
          predicates:
            - Path=/auth/**
          uri: http://localhost:9090
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/authservice

        - id: user-service
          predicates:
            - Path=/user/**
          uri: http://localhost:9091
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/userservice

        - id: company-service
          predicates:
            - Path=/company/**
          uri: http://localhost:9092
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/companyservice

        - id: financial-performance-service
          predicates:
            - Path=/financialperformance/**
          uri: http://localhost:9093
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/financialperformance

        - id: comment-service
          predicates:
            - Path=/comment/**
          uri: http://localhost:9094
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/commentservice
        - id: upcoming-payment-service
          predicates:
            - Path=/upcoming/**
          uri: http://localhost:9096
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/upcomingpaymentservice

        - id: shifts-and-breaks-service
          predicates:
            - Path=/shiftsandbreaks/**
          uri: http://localhost:9095
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/shiftsandbreaksservice
        - id: permission-service
          predicates:
            - Path=/permission/**
          uri: http://localhost:9011
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/permissionservice
        - id: expense-service
          predicates:
            - Path=/expense/**
          uri: http://localhost:9097
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/expenseservice
        - id: advance-payment-service
          predicates:
            - Path=/advancepayment/**
          uri: http://localhost:9098
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/advancepaymentservice
        - id: package-service
          predicates:
            - Path=/package/**
          uri: http://localhost:9099
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/packageservice

      default-filters:
        - RewritePath= /(?<segment>.*),/api/v1/$\{segment}