server:
  port: 9094

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${postgre}
    url: jdbc:postgresql://localhost:5432/hrms_commentservice
    hikari:
      maximum-pool-size: 2
      idle-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user


jwt:
  secretKey: ${java9secretkey}
  issuer: ${java9issuer}
  audience: ${java9audience}


rabbitmq: