server:
  port: 9012

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${postgre}
    url: jdbc:postgresql://localhost:5432/hrms_expenseservice
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


jwt:
  secretKey: ${java9secretkey}
  issuer: ${java9issuer}
  audience: ${java9audience}
